export const PRICE_CACHE_TTL_MS = 5_000;
export const COINBASE_RATE_LIMIT_MAX_REQUESTS = 10;
export const COINBASE_RATE_LIMIT_WINDOW_MS = 10_000;
export const COINBASE_RATE_LIMIT_IP_TTL_MS = 30_000;
export const EXTERNAL_REQUEST_TIMEOUT_MS = 15_000;
export const SIGNAL_STATE_TTL_MS = 5 * 60_000;
